export const ERROR_CATEGORY = {
    DOMAIN: "DOMAIN",
    VALIDATION: "VALIDATION",
    AUTH: "AUTH",
    PERMISSION: "PERMISSION",
    CONFLICT: "CONFLICT",
    NOT_FOUND: "NOT_FOUND",
    INFRA: "INFRA",
    DEPENDENCY: "DEPENDENCY",
    RATE_LIMIT: "RATE_LIMIT",
    UNKNOWN: "UNKNOWN",
} as const;

export type ERROR_CATEGORY = typeof ERROR_CATEGORY[keyof typeof ERROR_CATEGORY];
