export enum ERROR_CATEGORY {
    DOMAIN = "DOMAIN",
    VALIDATION = "VALIDATION",
    AUTH = "AUTH",
    PERMISSION = "PERMISSION",
    CONFLICT = "CONFLICT",
    NOT_FOUND = "NOT_FOUND",
    INFRA = "INFRA",
    DEPENDENCY = "DEPENDENCY",
    RATE_LIMIT = "RATE_LIMIT",
    UNKNOWN = "UNKNOWN",
}
